//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ado_muudel_Dotskin_Hirmumaja
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kasutaja
    {
        public int kasutajaId { get; set; }
        public string eesnimi { get; set; }
        public string parool { get; set; }
    }
}
